In [1]:
# import libraries
import pandas as pd
import numpy as np

import re
import string

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import nltk

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package stopwords to C:\Users\EXOTISCH
[nltk_data]     TECH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\EXOTISCH
[nltk_data]     TECH\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to C:\Users\EXOTISCH
[nltk_data]     TECH\AppData\Roaming\nltk_data...

True

In [2]:
df = pd.read_csv("/Users/EXOTISCH TECH/Desktop/Fake-Real-News-Project/data/processed/news.csv")

In [3]:
df.head()

,title,text,subject,date,label
0,It’s Really Happening: Trump Adviser Lays Out...,"Well, that didn t take long. In the short time...",News,2016-11-16,1
1,Republican attempt to deflect Trump-Russia pro...,(Reuters) - Republican lawmaker Devin Nunes’ i...,politicsNews,2017-09-11,0
2,Trump says churches should get FEMA funds for ...,WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,2017-09-09,0
3,Trump Loves To Say The New York Times Is ‘Fai...,Print journalism and longstanding papers have ...,News,2017-08-07,1
4,House Speaker Ryan briefed Trump on healthcare...,WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,2017-03-24,0

In [5]:
print("shape", df.shape)

shape (44898, 5)

In [6]:
# Remove the duplicate
print("Duplicates before:", df.duplicated().sum())

Duplicates before: 209

In [7]:
df = df.drop_duplicates().copy()

In [8]:
print("Duplicates after:", df.duplicated().sum())
print("New shape:", df.shape)

Duplicates after: 0
New shape: (44689, 5)

In [9]:
# combine title and article
df["title"] = df["title"].fillna("")
df["text"] = df["text"].fillna("")

In [10]:
df["article_content"] = (
    df["title"] + " " + df["text"]
)

In [11]:
# check the operation
df[["title", "text", "article_content"]].head()

,title,text,article_content
0,It’s Really Happening: Trump Adviser Lays Out...,"Well, that didn t take long. In the short time...",It’s Really Happening: Trump Adviser Lays Out...
1,Republican attempt to deflect Trump-Russia pro...,(Reuters) - Republican lawmaker Devin Nunes’ i...,Republican attempt to deflect Trump-Russia pro...
2,Trump says churches should get FEMA funds for ...,WASHINGTON (Reuters) - President Donald Trump ...,Trump says churches should get FEMA funds for ...
3,Trump Loves To Say The New York Times Is ‘Fai...,Print journalism and longstanding papers have ...,Trump Loves To Say The New York Times Is ‘Fai...
4,House Speaker Ryan briefed Trump on healthcare...,WASHINGTON (Reuters) - President Donald Trump ...,House Speaker Ryan briefed Trump on healthcare...

In [12]:
# build a text cleaning function
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = str(text).lower()
    
    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    
    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)
    
    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))
    
    # Remove numbers
    text = re.sub(r"\d+", "", text)
    
    # Tokenize
    words = text.split()
    
    # Remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]
    
    return " ".join(words)

In [13]:
df["clean_text"] = df["article_content"].apply(clean_text)

In [14]:
df.head()

,title,text,subject,date,label,article_content,clean_text
0,It’s Really Happening: Trump Adviser Lays Out...,"Well, that didn t take long. In the short time...",News,2016-11-16,1,It’s Really Happening: Trump Adviser Lays Out...,it’s really happening trump adviser lay plan n...
1,Republican attempt to deflect Trump-Russia pro...,(Reuters) - Republican lawmaker Devin Nunes’ i...,politicsNews,2017-09-11,0,Republican attempt to deflect Trump-Russia pro...,republican attempt deflect trumprussia probe c...
2,Trump says churches should get FEMA funds for ...,WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,2017-09-09,0,Trump says churches should get FEMA funds for ...,trump say church get fema fund hurricane relie...
3,Trump Loves To Say The New York Times Is ‘Fai...,Print journalism and longstanding papers have ...,News,2017-08-07,1,Trump Loves To Say The New York Times Is ‘Fai...,trump love say new york time ‘failing’ – effor...
4,House Speaker Ryan briefed Trump on healthcare...,WASHINGTON (Reuters) - President Donald Trump ...,politicsNews,2017-03-24,0,House Speaker Ryan briefed Trump on healthcare...,house speaker ryan briefed trump healthcare bi...

In [15]:
df[["article_content", "clean_text"]].head()

,article_content,clean_text
0,It’s Really Happening: Trump Adviser Lays Out...,it’s really happening trump adviser lay plan n...
1,Republican attempt to deflect Trump-Russia pro...,republican attempt deflect trumprussia probe c...
2,Trump says churches should get FEMA funds for ...,trump say church get fema fund hurricane relie...
3,Trump Loves To Say The New York Times Is ‘Fai...,trump love say new york time ‘failing’ – effor...
4,House Speaker Ryan briefed Trump on healthcare...,house speaker ryan briefed trump healthcare bi...

In [20]:
# save the dataframe
df.to_csv("/Users/EXOTISCH TECH/Desktop/Fake-Real-News-Project/data/processed/news_cleaned.csv", index = False)

In [19]:
print("Saved successfully!")

Saved successfully!